### ISSUE TITLE
Visual issue with Fondo on Xubuntu 19.10, installed through flatpak

### ISSUE THREAD

**Issue by JeffLabonte** [calo001/fondo#76]
Hey guys! 

First of all, I want to start off by saying that it is the first time I have an issue with the software and it is beautiful and well built, at least visually.

When I run the application from my Xubuntu machine, I am getting this thick black decoration as shown in the picture below!

![image](https://user-images.githubusercontent.com/9425955/70259998-614c2900-175d-11ea-9ae0-a4498f4540e4.png)

Cheers thanks!

**Comment by sudo-give-me-coffee** [comment]
Simply add 
```CSS
.titlebar {
  border-radius: 0;
}
decoration {
  border-radius: 0;
  box-shadow: none;
  margin:0;
  border: 1px solid @theme_bg_color;
}
````

On `${HOME}/.config/gtk-3.0/gtk.css`
